# Generated by Django 4.2.7 on 2023-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_remove_usuario_idade_usuario_confirmar_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_senha',
        ),
    ]
